"""initial schema: venues, events, seats, seat_state, sessions, orders, order_seats, sim_runs

Revision ID: 44a58b382023
Revises: 
Create Date: 2026-09-23 14:32:49.592830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a58b382023'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admission_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_token')
    )
    op.create_table('sim_runs',
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('invariant_violations', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('seed')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('layout_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('onsale_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('row', sa.String(length=16), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('price_tier', sa.String(length=32), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='static seat inventory; one row per physical seat'
    )
    op.create_table('order_seats',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'seat_id')
    )
    op.create_table('seat_state',
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('held_by_session', sa.UUID(), nullable=True),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'available' AND held_by_session IS NULL AND held_until IS NULL) OR (status = 'held' AND held_by_session IS NOT NULL AND held_until IS NOT NULL) OR (status = 'sold' AND held_by_session IS NOT NULL AND held_until IS NULL)", name='ck_seat_state_status_fields_consistent'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['held_by_session'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('seat_id', 'event_id')
    )
    op.create_index('ix_seat_state_event_status', 'seat_state', ['event_id', 'status'], unique=False)
    op.create_index('ix_seat_state_held_until', 'seat_state', ['held_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seat_state_held_until', table_name='seat_state')
    op.drop_index('ix_seat_state_event_status', table_name='seat_state')
    op.drop_table('seat_state')
    op.drop_table('order_seats')
    op.drop_table('seats')
    op.drop_table('orders')
    op.drop_table('events')
    op.drop_table('venues')
    op.drop_table('sim_runs')
    op.drop_table('sessions')
    # ### end Alembic commands ###
